### ISSUE TITLE
install with hacs fails

### ISSUE THREAD

**Issue by wimpie007** [fwestenberg/reolink#1]
install with hacs fails
since 0.02...?

**Comment by fwestenberg** [comment]
Bummer, I moved the custom component because ai've planned to release an official HA integration.

**Comment by DKFrederik** [comment]
I also get a fail when updating the component. then I unistalled the integration to try a a fresh installation but no luck. Now It can't install at all.

**Comment by fwestenberg** [comment]
For the time being, just download the zip here: https://github.com/fwestenberg/reolink_dev and add the reolink_dev subfolder into your custom_components folder of HA.

**Comment by wimpie007** [comment]
ok, done it that way for now.
Thanks!

**Comment by wimpie007** [comment]
@fwestenberg  would you be so kind to leave a message here when we can install the repo again through hacs?
Thanks!

**Comment by andriej** [comment]
I keep fingers crossed for the official HA integration!

**Comment by fwestenberg** [comment]
Thanks!!
