### ISSUE TITLE
Changing to rtsp doesn't do anything

### ISSUE THREAD

**Issue by mrand** [fwestenberg/reolink#11]
**Describe the bug**
Tried to change the integration from rtmp to rtsp to see if it helps with the stream errors / timeouts I'm getting.  But the integration never seems to change

**To Reproduce**
After adding integration, go to the integration options and attempt to change to rtsp.  It doesn't seem to apply.

**Expected behavior**
When selectiong rtsp and clicking "submit", integration remembers that I selected rtsp.

**Screenshots**
![image](https://user-images.githubusercontent.com/435987/101926250-8d805e00-3b98-11eb-87f7-37dc0a2df08b.png)

**Environment:**

- Home Assistant version: 0.118.4
- Model RLC-511W
- Build No. build 20103104
- Hardware No. IPC_51516M5M
- Config Version v3.0.0.0
- Firmware Version v3.0.0.116_20103104

**Additional context**

Log seems to indicate still using rtmp:
2020-12-11 10:01:10 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtmp://192.168.2.20:1935/bcs/channel0_main.bcs?channel=0&stream=0&token=<token_string>

**Comment by fwestenberg** [comment]
Thanks, in HACS v0.9 I already removed this option.

**Comment by mrand** [comment]
Oh no :-(   I was needing to use it because rtsp works great wirelessly, while rtmp hangs (even with VLC).
