### ISSUE TITLE
Reolink_dev

### ISSUE THREAD

**Issue by FR1990** [fwestenberg/reolink#12]
I have a failure with the RTSP, since in the configuration.yaml I put the ip and http port, when the rtsp opens I get the ip with the http port, because I have it written in the configuration.yaml
Is there a way to add the HTTP port without RTSP detecting it?

configuration.yaml

    platform: reolink_dev
    host: IP_ADDRESS_:PORT_HTTP
    username: USERNAME_ADMIN
    password: YOUR_PASSWORD
    name: Reolink Camera
    stream: main
    protocol: rtsp 
    channel: 0
    scan_interval: 5

Stream connection failed: rtsp://USERNAME_ADMIN:YOUR_PASSWORD@IP_ADDRESS_:PORT_HTTP:PORT_RTSP/h264Preview_01_main

**Comment by fwestenberg** [comment]
It looks like you are using an old version? In the new version you should use the config flow.
Also, why do you use RTSP for streaming?

**Comment by fwestenberg** [comment]
Please use the bug report template.

**Comment by FR1990** [comment]
The RTSP, watch live

The new version where do I put the new configuration files?

**Comment by FR1990** [comment]
Yes, old version

**Comment by fwestenberg** [comment]
You can config it from the integration flow. So no config files needed anymore.
