### ISSUE TITLE
New versione error: reolink_dev not found

### ISSUE THREAD

**Issue by baddy-0** [fwestenberg/reolink#12]
I follwed the instruction to install new version but log tells
Platform error camera.reolink_dev - Integration 'reolink_dev' not found.

**Comment by Kaibob2** [comment]
Same here:
https://github.com/fwestenberg/reolink/issues/2#issuecomment-559474193

**Comment by baddy-0** [comment]
My tree installation is 
reolink_dev/
├── camera.py
├── manifest.json
├── ReolinkPyPi
│   └── camera.py
└── services.yaml
and HA does not create __init.py__ or pycache
Configuration.yaml is
  - platform: reolink_dev
    name: davanti
    host: 192.168.1.69
    username: admin
    password: !secret gw2-account-pass
    scan_interval: 5
Thank you

**Comment by fwestenberg** [comment]
Can you please update the content of your manifest.json with this (just) [updated version ](https://github.com/fwestenberg/reolink/blob/master/custom_components/reolink/manifest.json)and restart HA?

**Comment by fwestenberg** [comment]
> My tree installation is
> reolink_dev/
> ├── camera.py
> ├── manifest.json
> ├── ReolinkPyPi
> │   └── camera.py
> └── services.yaml
> and HA does not create **init.py** or pycache
> Configuration.yaml is
> 
> * platform: reolink_dev
>   name: davanti
>   host: 192.168.1.69
>   username: admin
>   password: !secret gw2-account-pass
>   scan_interval: 5
>   Thank you

Also `__init__,py` is not created by HA, you have to copy the files from the Reolink git directory or just create the two empty files in the directory. More info on this [here](https://pythontips.com/2013/07/28/what-is-__init__-py/).

**Comment by fwestenberg** [comment]
Github didn’t like the empty files. So now there is a comment line in it. I added the __init__.py files to the git repository.
