### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by FR1990** [fwestenberg/reolink#15]
copy to \config:

.github/ISSUE_TEMPLATE
reolink
license
README.md
setup.cfg
setup.py
test.py

----------------
this goes in the configuration.yaml? and to add multiple cameras
----------------

api = camera_api.Api('192.168.1.10', 80, 'user', 'mypassword')
 get settings, like ports etc.:
await api.get_settings()

 Store the subscribe   ##port
subscribe_port =  api.onvif_port

 get the states:
await api.get_states()

 print some state value:
print(api.ir_state)

 enable the infrared lights:
await api.set_ir_lights(True)

 logout
await api.logout()

 Now subscribe to events, suppose our webhook url is http://192.168.1.11/webhook123

sman = subscription_manager.Manager('192.168.1.10', subscribePort, ' user', 'mypassword')
await sman.subscribe('http://192.168.1.11/webhook123')

 After some minutes check the renew timer (keep the eventing alive):
if (sman.renewTimer <= 100):
await sman.renew()

 Unsubscribe
await sman.unsubscribe()

------------------------------------------

**Comment by fwestenberg** [comment]
What are you trying to do?

**Comment by FR1990** [comment]
I want to add Reolink cameras to HA, but this system does not know how it works, the previous version was easy and everything was explained, this one I don't understand.

I wanted to add 3 cameras

**Comment by fwestenberg** [comment]
Go to my right library: reolink_dev instead of reolink. Read the readme there. It's very clear I think.
