### ISSUE TITLE
Port missing in uri

### ISSUE THREAD

**Issue by dkramer74** [fwestenberg/reolink#15]
Latest update fixed my previous issue but now I am receiving:

Port missing in uri

on both my RLC-410, installed component via HACS

**Comment by fwestenberg** [comment]
Please post your config. And how are the ports configured in your camera?

**Comment by dkramer74** [comment]
```
- platform: reolink_dev
    name: entry
    host: 192.168.1.xxx
    username: admin
    password: !secret entry_cam_pass
    scan_interval: 5
```

The ports are default I believe.

Media: 9000
HTTP: 80
RTSP: 554

**Comment by fwestenberg** [comment]
The camera stream is using the RTMP port from the camera config. So first it will query the ports from your camera and use those ports. Is the RTMP port also filled in correctly?

**Comment by fwestenberg** [comment]
Can you please check if this is still actual with the latest PR?

**Comment by fwestenberg** [comment]
Please check my post [here](https://github.com/fwestenberg/reolink/issues/21#issuecomment-570146050). If you change the protocol to rtsp, does the stream work?

**Comment by dkramer74** [comment]
The latest update fixed the issue, all my cameras are working perfectly now, thank you!

**Comment by dkramer74** [comment]
Spoke too soon, still the same error even when using rtsp. I don't see a rtmp port setting anywhere on my cameras

**Comment by dkramer74** [comment]
searching for the RTMP port got my thinking I need to update firmware on the cameras, did that and all is fine now.

**Comment by fwestenberg** [comment]
Good to know! Thanks.
