### ISSUE TITLE
Motion detection on/off

### ISSUE THREAD

**Issue by heilloos** [fwestenberg/reolink#16]
In the current items I did not see a switch to set Motion detection to ON or OFF.
Via this feature it´s possible to create automation to set it off when your home and on when you are away.

I already searched for CGI commands, but these seem to be unavailable.

**Comment by fwestenberg** [comment]
I don't see this in the Reolink API either. Also, I think a better approach would be to create a group with motion sensors in HA (if you have multiple) and add a Alarm control panel to HA. The automation for the alarm panel can watch the sensors when you want to.

**Comment by fwestenberg** [comment]
Otherwise, just switch off the automation when you are home. :)

**Comment by heilloos** [comment]
Thanks

 

Regards

Hans

 

Van: fwestenberg [mailto:notifications@github.com] 
Verzonden: woensdag 4 december 2019 12:16
Aan: fwestenberg/reolink <reolink@noreply.github.com>
CC: heilloos <hans@hofstee.nu>; Author <author@noreply.github.com>
Onderwerp: Re: [fwestenberg/reolink] Motion detection on/off (#16)

 

Closed #16 <https://github.com/fwestenberg/reolink/issues/16> .
