### ISSUE TITLE
Component crash after reboot Camera

### ISSUE THREAD

**Issue by Imperial-Guard** [fwestenberg/reolink#19]
I had at the beginning some issues with my Reolink Camera, not sure if this wass firmware related but I have still a daily reboot activated on my camera.

What I've noticed is that this  component is crashing once there is no connection with the camera.

**Comment by mihalski** [comment]
I have the same problem when I restart the camera. In fact the crash of the component brings down Home Assistant with it :/

**Comment by fwestenberg** [comment]
Can you post you log please? I'm wondering what makes HA crash.

**Comment by Imperial-Guard** [comment]
Was looking trough my logs I think this should be related

`Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                          421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line                                                                          416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
`

**Comment by fwestenberg** [comment]
You are right, improved the exception handling solved this issue.

**Comment by Imperial-Guard** [comment]
Home Assistant is still crashing when the camera is rebooting, just tried it once again. 

Tried to provide you a log but that was not possible.

**Comment by fwestenberg** [comment]
Did you update alle both files in your custom components folder? First it was crashing here also, but after the fix not...

**Comment by Imperial-Guard** [comment]
Yes even with the latest version. 

I'm using a RLC-410W and a RLC-422 (both connected via ethernet)

**Comment by fwestenberg** [comment]
In my case I see it's not reconnecting after a camera restart. My HA does not crash anymore. Probably the token is not valid after the reboot.

**Comment by fbrinker** [comment]
I have to assume that this component causes my HA crashes too, when i disconnect the camera (pulling the power plug)... I didn't have any crashes before.

It doesn't crash instantly, but after ~15 minutes. The thing is... it does not crash every time I disconnect the camera... so I have to investigate further into this.

But the last words of my HA instance before the last crash were the following:
![](https://images.f-brinker.de/images/2020/01/18/DeepinBildschirmfoto_Bereich-auswahlen_20200118002857.png)

I will collect more data and report any new crashes :)

**Comment by fwestenberg** [comment]
This looks like the HA shutdown/restart is called by the user or some other way. The Reolink component is registered to the shutdown event and calls the disconnect method. And now we're just looking at a wrong handling of the response. So it's unlikely the Reolink component is causing the crash.

**Comment by fbrinker** [comment]
Good to know, thank you :)
The "disconnecting" msg confused me and was new to me :+1:
