### ISSUE TITLE
Error Setting Up Platform

### ISSUE THREAD

**Issue by dkramer74** [fwestenberg/reolink#2]
Receiving the following error with this component

`Error while setting up platform reolink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/reolink/camera.py", line 52, in async_setup_platform
    reolinkCameraDevice = ReolinkCamera(hass, config)
  File "/config/custom_components/reolink/camera.py", line 130, in __init__
    self._reolink_session = Camera(self._host, self._username, self._password)
  File "/config/custom_components/reolink/ReolinkCamera.py", line 163, in __init__
    super(Camera, self).login(self.username, self.password)
  File "/config/custom_components/reolink/ReolinkCamera.py", line 27, in login
    data = json.loads(response.text)[0]
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by fwestenberg** [comment]
Seems like the login doesn't get the expected result. Are you sure the credentials are correct in the configuration.yaml? Which camera type do you have?

**Comment by dkramer74** [comment]
Credentials are correct, using the same ones that work with the generic camera component.
Camera is RLC-410

**Comment by MichaelRoxin** [comment]
Same here. RLC-410 with hassio 0.1002 and have done installation via HACS but still get  the integration not found.

**Comment by hmmatos** [comment]
same here 
Platform error camera.reolink - Integration 'reolink' not found.

**Comment by fwestenberg** [comment]
Can you please verify if this issue is still actual with the latest vesion?

**Comment by Kaibob2** [comment]
I got my Reolink E1 a week ago. I checked the version from a few days ago and had the same error. 
Today with the new version i get the following error in the Log.
![Unbenannt](https://user-images.githubusercontent.com/20832276/69805831-da89d000-11e1-11ea-8aec-fa159ad5d331.JPG)

In configuration.yaml i have:
````
camera:
- platform: reolink 
  name: ipcam
  host: 192.168.0.22
  username: admin
  password: 123456789
  scan_interval: 5
````

**Comment by fwestenberg** [comment]
Please check your folder structure as mentioned [here](https://community.home-assistant.io/t/reolink-poe-ip-camera-setup/122890/94?u=fwestenberg). This should fix it.

**Comment by Kaibob2** [comment]
Ich changed the directory structure to 

![a9bc8d0ec7af1a8ab552a081f4627f52710854bc](https://user-images.githubusercontent.com/20832276/69867372-d4a9f280-12a6-11ea-866f-856e624bc9c6.png)

and added an empty `__init__.py` file into the `reolink_dev` and the `ReolinkPyPi` directory.
Now the error after reboot is

![Unbenannt](https://user-images.githubusercontent.com/20832276/69867445-15097080-12a7-11ea-9d26-c495fed6ebbb.JPG)

Configuration.yaml is still

```
camera:
- platform: reolink 
  name: ipcam
  host: 192.168.0.22
  username: admin
  password: 123456789
  scan_interval: 5
```

**Comment by fwestenberg** [comment]
I'm sorry, forgot to tell that ffmpeg is required for the camera stream. Just add `ffmpeg:` to your configuration.yaml, like described [here](https://www.home-assistant.io/integrations/ffmpeg/).

**Comment by Kaibob2** [comment]
Nice. Thanks for the support. The integration itself seems to be running now. But i stil get the folowing errors
![Unbenannt](https://user-images.githubusercontent.com/20832276/69872380-89e3a700-12b5-11ea-98d6-f058c52c8933.JPG)

![Unbenannt2](https://user-images.githubusercontent.com/20832276/69872387-8e0fc480-12b5-11ea-9633-232f4d7c067f.JPG)

![Unbenannt3](https://user-images.githubusercontent.com/20832276/69872393-923be200-12b5-11ea-8d42-624b61874d44.JPG)

**Comment by Kaibob2** [comment]
I'm not absolutely sure if this is some network issue. I'm unable to connect to the E1 via any browser. Using the Reolink Windows client works flawless, no matter if connecting via UID or IP. The IP is correct and the media Port is set to (default) 9000. RTSP is set to 554.

**Comment by fwestenberg** [comment]
If you take a look [here](https://support.reolink.com/hc/en-us/articles/360007011233-How-to-Capture-Live-JPEG-Image-of-Reolink-Cameras-via-Web-Browsers) you'll find your camera does not support this image url..  Any idea what the image url might be?

**Comment by Kaibob2** [comment]
I contacted the support and asked for it. There are no hints across the internet regarding the URL for the E1. I already searched before.

**Comment by fwestenberg** [comment]
I think this issue is more related to the E1 cam than the integration itself. As soon as there is an URL available let me know. For the time being if you are using the [picture glance card ](https://www.home-assistant.io/lovelace/picture-glance/)like in my example, you can set it to live view (instead of snapshot), or just add a fixed image.

**Comment by Kaibob2** [comment]
Only for completeness. The E1 does not provide any access via URL nor RTSP. Only the App or the Reolink client can access the camera. This is what the support answered me. Sad but true :)

**Comment by fwestenberg** [comment]
Thanks for the info.

**Comment by mwegener-com** [comment]
> Only for completeness. The E1 does not provide any access via URL nor RTSP. Only the App or the Reolink client can access the camera. This is what the support answered me. Sad but true :)

If I take a look at the reolink website, they say that RTSP for E1 Pro can be used?
https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

**Comment by Kaibob2** [comment]
We were discussing about the E1 without the "pro".

**Comment by Kaibob2** [comment]
In the Link you provided it clearly says:
Applies to: All Reolink IP cameras( Reolink E1 pro and E1 zoom included) **except for** battery-powered cameras and B800/D800/B400/D400/**E1**/ Reolink Lumus.
