### ISSUE TITLE
Image quality stream in Home Assistant

### ISSUE THREAD

**Issue by Imperial-Guard** [fwestenberg/reolink#21]
First of all once again thanks for your great work and fixing the previous issue. 

Currently I'm testen the updated version and what I've noticed is that the image quality is quite low somehow. 

The following things what I've done to exclude if it is maybe related to the netwerk: 

- Stopped the MotionEye container, where I also use the RTMP stream
- Removed the generic camera component in Home Assistant with the RTMP stream. 

Is there a way to change the image quality? 

I've checked a part of your code but the url what you're using is in the same way as I used it in the generic camera component: "rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password"

Not sure if this is related but the following error will appear in Home Assistant: 

Log Details (ERROR)
Thu Jan 02 2020 08:18:25 GMT+0100 (Midden-Europese standaardtijd)
Error requesting stream: camera.achtertuin_reolink does not support play stream service

**Comment by Imperial-Guard** [comment]
Also attached some logs

`[36m2020-01-02 08:26:36 DEBUG (SyncWorker_9) [homeassistant.util.json] JSON file not found: /config/custom_components/reolink_dev/.translations/camera.en.json[0m
[36m2020-01-02 08:26:38 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy_stream/camera.achtertuin_reolink to 172.17.0.7 (auth: False)[0m
[36m2020-01-02 08:26:44 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:26:36.069193+01:00, last_update=2020-01-02T09:26:08.083411+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:26:08.167359+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:26:43.972918+01:00, last_update=2020-01-02T09:26:44.027364+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:26:08.167359+01:00>>}[0m
[36m2020-01-02 08:26:44 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501030888656] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:26:36.069193+01:00, last_update=2020-01-02T09:26:08.083411+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:26:08.167359+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:26:43.972918+01:00, last_update=2020-01-02T09:26:44.027364+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:26:08.167359+01:00>>}[0m
[36m2020-01-02 08:26:45 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Received {'type': 'auth/sign_path', 'path': '/api/camera_proxy/camera.achtertuin_reolink', 'id': 23}[0m
[36m2020-01-02 08:26:45 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 23, 'type': 'result', 'success': True, 'result': {'path': '/api/camera_proxy/camera.achtertuin_reolink?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzk2OGEzMjVlMWQ0MjQ0YWFkNTZhMjQ1ZTc0Y2E3YyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWNodGVydHVpbl9yZW9saW5rIiwiaWF0IjoxNTc3OTUwMDA1LCJleHAiOjE1Nzc5NTAwMzV9.CfZJDNljRf7RybBfpRhlLoJwuZKxF-r1sQ9zfiIvZEI'}}[0m
[36m2020-01-02 08:26:45 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:28:22 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:28:22 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.achtertuin_reolink to 172.17.0.7 (auth: True)[0m
[36m2020-01-02 08:28:23 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:17.020129+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:23 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:17.020129+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:25 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets= @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:25 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=False, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets= @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:25 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'config/entity_registry/get', 'entity_id': 'camera.achtertuin_reolink', 'id': 39}[0m
[36m2020-01-02 08:28:25 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy_stream/camera.achtertuin_reolink to 172.17.0.7 (auth: False)[0m
[36m2020-01-02 08:28:29 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets= @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:29.018766+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:29 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:23.114376+01:00, last_update=2020-01-02T09:27:53.853965+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets= @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:29.018766+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:32 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'auth/sign_path', 'path': '/api/camera_proxy/camera.achtertuin_reolink', 'id': 40}[0m
[36m2020-01-02 08:28:32 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 40, 'type': 'result', 'success': True, 'result': {'path': '/api/camera_proxy/camera.achtertuin_reolink?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzk2OGEzMjVlMWQ0MjQ0YWFkNTZhMjQ1ZTc0Y2E3YyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWNodGVydHVpbl9yZW9saW5rIiwiaWF0IjoxNTc3OTUwMTEyLCJleHAiOjE1Nzc5NTAxNDJ9.6O0L5ZbtKklTDaHqYzY0xHw3S7GrIq5osZyevc2O3a4'}}[0m
[36m2020-01-02 08:28:32 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:28:32 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.achtertuin_reolink to 172.17.0.7 (auth: True)[0m
[36m2020-01-02 08:28:35 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:29.018766+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:35.018053+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:35 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:29.018766+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:35.018053+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:35.018053+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:35.018053+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>>}[0m
[36m2020-01-02 08:28:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'auth/sign_path', 'path': '/api/camera_proxy/camera.achtertuin_reolink', 'id': 41}[0m
[36m2020-01-02 08:28:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 41, 'type': 'result', 'success': True, 'result': {'path': '/api/camera_proxy/camera.achtertuin_reolink?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzk2OGEzMjVlMWQ0MjQ0YWFkNTZhMjQ1ZTc0Y2E3YyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWNodGVydHVpbl9yZW9saW5rIiwiaWF0IjoxNTc3OTUwMTIyLCJleHAiOjE1Nzc5NTAxNTJ9.avBjDNP7ieDiqgmV3iNO4DXJxZvFPxb1w4M3RWvOQGk'}}[0m
[36m2020-01-02 08:28:42 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:28:42 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.achtertuin_reolink to 172.17.0.7 (auth: True)[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=no_motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:28:47.020637+01:00>>}[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:27:54.149718+01:00>, new_state=<state camera.achtertuin_reolink=no_motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lights_enabled=True, ptzpresets=, friendly_name=Achtertuin Reolink, entity_picture=/api/camera_proxy/camera.achtertuin_reolink?token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, supported_features=2 @ 2020-01-02T08:28:47.020637+01:00>>}[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'config/entity_registry/get', 'entity_id': 'camera.achtertuin_reolink', 'id': 42}[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'camera/stream', 'entity_id': 'camera.achtertuin_reolink', 'id': 43}[0m
[31m2020-01-02 08:28:47 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.achtertuin_reolink does not support play stream service[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 43, 'type': 'result', 'success': False, 'error': {'code': 'start_stream_failed', 'message': 'camera.achtertuin_reolink does not support play stream service'}}[0m
[36m2020-01-02 08:28:47 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy_stream/camera.achtertuin_reolink to 172.17.0.7 (auth: False)[0m
[36m2020-01-02 08:28:52 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'auth/sign_path', 'path': '/api/camera_proxy/camera.achtertuin_reolink', 'id': 44}[0m
[36m2020-01-02 08:28:52 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 44, 'type': 'result', 'success': True, 'result': {'path': '/api/camera_proxy/camera.achtertuin_reolink?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzk2OGEzMjVlMWQ0MjQ0YWFkNTZhMjQ1ZTc0Y2E3YyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWNodGVydHVpbl9yZW9saW5rIiwiaWF0IjoxNTc3OTUwMTMyLCJleHAiOjE1Nzc5NTAxNjJ9.JXL1MSkxaQV788WXheEm_G00tyEdJAXkKFzaNyVDdDA'}}[0m
[36m2020-01-02 08:28:52 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:28:52 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.achtertuin_reolink to 172.17.0.7 (auth: True)[0m
[36m2020-01-02 08:29:02 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Received {'type': 'auth/sign_path', 'path': '/api/camera_proxy/camera.achtertuin_reolink', 'id': 45}[0m
[36m2020-01-02 08:29:02 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501025250256] Sending {'id': 45, 'type': 'result', 'success': True, 'result': {'path': '/api/camera_proxy/camera.achtertuin_reolink?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmNzk2OGEzMjVlMWQ0MjQ0YWFkNTZhMjQ1ZTc0Y2E3YyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuYWNodGVydHVpbl9yZW9saW5rIiwiaWF0IjoxNTc3OTUwMTQyLCJleHAiOjE1Nzc5NTAxNzJ9.NiR4aUyQmf1OclXG-Be2LRfy4BhWW5RDS_dsogM6XIo'}}[0m
[36m2020-01-02 08:29:02 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.7 for /api/camera_proxy/camera.achtertuin_reolink using signed request[0m
[36m2020-01-02 08:29:02 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.achtertuin_reolink to 172.17.0.7 (auth: True)[0m
[36m2020-01-02 08:29:05 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140501026140112] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=camera.achtertuin_reolink, old_state=<state camera.achtertuin_reolink=no_motion; access_token=1f955451e2f55917973d337c7384e342a3a4abf70a6666e80ce09655c71ed8f1, last_motion=2020-01-02T09:28:41.021265+01:00, last_update=2020-01-02T09:28:29.077884+01:00, ftp_enabled=False, email_enabled=True, ir_lig
`

**Comment by fwestenberg** [comment]
I've updated the integration a bit, play stream should be supported now. Also there are two new optional parameters available: stream and protocol (see the readme):

camera:
- platform: reolink_dev
  host: IP_ADDRESS
  username: admin
  password: YOUR_PASSWORD
  name: camera (optional, default Reolink Camera)
  **stream**: main or sub (optional, default main)
  **protocol**: rtmp or rtsp (optional, default rtmp)
  scan_interval: 5 (optional, default 30s)

For image quality you'll probably have to check how the streams are setup in the configuration of the camera. You can specify the quality for the main and sub (balanced) stream there. Please keep me informed!
