### ISSUE TITLE
Problem integrating the NVR on the HA Home Assistant

### ISSUE THREAD

**Issue by MiAutomations** [fwestenberg/reolink#23]
Hello First of all thank you for your work and support

I'm facing a issue when I try to add the NVR over the reolink integration available on the HA Home Assistant as you can view in the picture bellow 

![image](https://user-images.githubusercontent.com/47602733/105916250-8cac6a00-6028-11eb-800f-a29ed37ad634.png)

The NVR model is the RLN16-410 and the addon version is the last one v0.13 

Can you please help in order to solve this issue ? 

Thank you and best regards

**Comment by fwestenberg** [comment]
Hi, do you have any logging available?

**Comment by MiAutomations** [comment]
> Hi, do you have any logging available?

I don't see any thing related to this on the logs ... Is there any way to check ?

Thank you for your support

**Comment by fwestenberg** [comment]
Please log your HA related issues at: https://github.com/fwestenberg/reolink_dev please. Thanks.
