### ISSUE TITLE
Repostitory structure for v0015 is not compliant

### ISSUE THREAD

**Issue by twangraus** [fwestenberg/reolink#24]
**Describe the bug**
It seems to be that using the latest version (v0015) in HACS is not working. When downloading the the custom repositories in HACS with following URL (https://github.com/fwestenberg/reolink) gives the error Repostitory structure for v0015 is not compliant

**To Reproduce**
Add the newest implementation using the custom repositories in HACS

**Expected behavior**
The reolink repositories to download

**Screenshots**
![image](https://user-images.githubusercontent.com/27231365/106352241-9ca2a300-62e1-11eb-883f-2f926edea1d7.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: Home Assistant OS 5.10
 - Reolink camera model: N/A
 - Camera firmware number: N/A

**Additional context**

**Comment by alouettehome** [comment]
Also having this issue. Except it now says " Repostitory structure for v0016 is not compliant"

**Comment by twangraus** [comment]
This has to do with the fact that currently version 0.16 is released, but still same message
<img width="1284" alt="Schermafbeelding 2021-02-16 om 19 24 59" src="https://user-images.githubusercontent.com/27231365/108107074-0915f400-708f-11eb-84bf-2ae2ab2196e5.png">

**Comment by fwestenberg** [comment]
Just read here: https://github.com/fwestenberg/reolink/issues/20
