### ISSUE TITLE
Reolink issues accessing the API

### ISSUE THREAD

**Issue by gregoryduckworth** [fwestenberg/reolink#24]
Since the latest commit (4661784) I have been getting the error:

`Exception while calling Reolink camera API at ip 192.168.1.10`

And the stream only has the last few seconds before the error occurred.

This is directly accessing the camera and not using an NVR.

**Comment by gregoryduckworth** [comment]
Restarting HA solves the issue and haven't been able to reproduce it as of yet.

**Comment by fwestenberg** [comment]
Yes, after updating the component you should reboot HA to see the effect of the change. Thanks!

**Comment by gregoryduckworth** [comment]
I had restarted and then got the error but a second restart solved the issue.
