### ISSUE TITLE
RLC-810A Stream not supported

### ISSUE THREAD

**Issue by LasseSLambertsen** [fwestenberg/reolink#25]
Hi, streaming from RLC-810A is not supported, as the main stream url on this device is:
rtsp://admin:111111@192.168.0.110:554//h265Preview_01_main

https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

**Comment by fwestenberg** [comment]
Did you try to select the RTSP protocol from the options menu at the integrations page?

**Comment by LasseSLambertsen** [comment]
Yes, i belive the issue is:
https://github.com/fwestenberg/reolink/blob/main/reolink/camera_api.py#L393

I've just added a pull request

**Comment by fwestenberg** [comment]
I see now they support 264 or 265 depending on the camera model, right?

**Comment by LasseSLambertsen** [comment]
Yea, exactly :)
Sounds like all future 8mp cameras will use 265 on the main stream

**Comment by fwestenberg** [comment]
You can always use RTMP for the time being. It reuses the API token, so it's more secure than the user+pass combination in the RTSP url.
