### ISSUE TITLE
Reolink E1 Pro unsupported?

### ISSUE THREAD

**Issue by artaxx81** [fwestenberg/reolink#29]
Hi there,

I hope that I am not right, but it is possible that the E1 Pro is unsupported by your plugin?

That's my configuration.yaml:

```
- platform: reolink_dev
  host: 192.168.0.127
  username: admin
  password: xxx
  name: Wohnung_Test
```
In my conditions I get from the camera:

```
access_token: 74ca9fb8e291944c206c4097a790ffe41b3bc99205d8524aba4980c2d2e1c8a8
last_update: 2020-02-05T13:01:03.079608
ftp_enabled: null
email_enabled: null
ir_lights_enabled: null
ptzpresets: {}
friendly_name: Wohnung_Test
entity_picture: /api/camera_proxy/camera.wohnung_test?token=74ca9fb8e291944c206c4097a790ffe41b3bc99205d8524aba4980c2d2e1c8a8
supported_features: 2
```

and state:

`no_motion`

State isn't changing with motion!

Do you have an idea what might be wrong?

Thank you!

Greets
Daniel

**Comment by bocsitomcsi** [comment]
I can confirm that the component is not working with E1 Pro on my side as well. I am not really sure about the problem but it looks like it cannot even use API toward it:

```
2020-02-06 14:02:28,437 - MainThread - custom_components.reolink_dev.ReolinkPyPi.camera - ERROR - Exception while calling Reolink camera API at ip 192.168.0.53
2020-02-06 14:02:28,437 - MainThread - custom_components.reolink_dev.ReolinkPyPi.camera - ERROR - Error translating login response to json
```

I have read somewhere in reolink doc that E1 Pro does not have any webserver, can it be the problem? I guess still some API request should work.

**Comment by geraldhansen** [comment]
I run into the same issue.
Would be nice if you can provide a list which reolink cameras you tested or with which cameras this is working well.
Thanks.

**Comment by fwestenberg** [comment]
Thanks for your info. I added a small list of known unsupported models to the readme.

**Comment by mwegener-com** [comment]
> Thanks for your info. I added a small list of known unsupported models to the readme.

Could you explain why E1 PRO is not supported? What is the issue with this device?
