### ISSUE TITLE
Automation Notification with snapshot?

### ISSUE THREAD

**Issue by JohnGalt1717** [fwestenberg/reolink#35]
I cannot get this working for the life of me. What would an automation look like that when there's motion sends a notification with a a snap shot?

**Comment by fwestenberg** [comment]
It should be something like:

trigger:
![image](https://user-images.githubusercontent.com/47930023/80861103-af158080-8c6c-11ea-9aeb-b00b59589ab9.png)

action:
![image](https://user-images.githubusercontent.com/47930023/80861116-bccb0600-8c6c-11ea-8321-b84a55171546.png)

**Comment by JohnGalt1717** [comment]
Ok, that all makes sense but I don't know how to send the snapshot to my notifer (phone)

**Comment by fwestenberg** [comment]
This depends on what notifier service you use. I'm using Pushover, you can send an attachment with the message.
