### ISSUE TITLE
Detection of blocking I/O in the event loop

### ISSUE THREAD

**Issue by silfa718** [fwestenberg/reolink#37]
Using the the .109.0 Beta I get this in my logs:

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 7:24:43 AM (847 occurrences)
Last logged: 7:36:38 AM
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for reolink_dev doing I/O at custom_components/reolink_dev/ReolinkPyPi/camera.py, line 282: response = requests.post(self._url, data=json.dumps(body), params=param, timeout=10)

**Comment by Sjeff** [comment]
got one more after updating to 0.109.0 (stable)

```
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for reolink_dev doing I/O at custom_components/reolink_dev/ReolinkPyPi/camera.py, line 280: response = requests.get(self._url, params=param, stream=stream, timeout=10)
```

**Comment by vager88** [comment]
This is happening for me as well.. Just updated to 0.109.0 last night.
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for reolink_dev doing I/O at custom_components/reolink_dev/ReolinkPyPi/camera.py, line 282: response = requests.post(self._url, data=json.dumps(body), params=param, timeout=10)

The camera's appear to still be working, it's just this new log message.. Which from reading the notes is a new feature to be able to provide more details.

**Comment by gregoryduckworth** [comment]
Would love to get this looked at, getting quite a few occurences of it.
```
First occurred: April 30, 2020, 10:05:37 PM (43021 occurrences)
```

**Comment by fwestenberg** [comment]
SInce HA 0.109 blocking i/o is detected. This is fixed in the latest master.

**Comment by gregoryduckworth** [comment]
I installed the latest version and am now getting the error:
```
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/camera.py", line 290, in update_status
    await self.hass.async_add_executor_job(self._reolinkSession.status())
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable
```
