### ISSUE TITLE
Missing width and height (home assistant 2021.9.0)

### ISSUE THREAD

**Issue by marcob79** [fwestenberg/reolink#39]
After upgrading home assistant to version 2021.9.0, the following error appear as per new changes in latest home assistant release

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Camera (documentation, issues)
First occurred: September 1, 2021, 11:49:15 PM (1 occurrences)
Last logged: September 1, 2021, 11:49:15 PM

The camera entity camera.box does not support requesting width and height, please open an issue with the integration author

**Comment by fwestenberg** [comment]
This will be fixed in the reolink_dev repository.
