### ISSUE TITLE
repo into hacs??

### ISSUE THREAD

**Issue by upwindanderl** [fwestenberg/reolink#39]
wuaaaowh! 
what an awesome integration! I was searching for smth like this for hours now. 

Is it planned to bring the integration into hacs? :) 
https://github.com/hacs/integration

**Comment by gregoryduckworth** [comment]
You can add the repo as a custom repository into HACS.

**Comment by upwindanderl** [comment]
> You can add the repo as a custom repository into HACS.

hmmmm... i guess i'm not able to do it ^^
may you give a short hint how? :)

**Comment by gregoryduckworth** [comment]
On the HACS page on your instance there is a settings tab where you can add them.

![289F6DC8-3F49-4F1B-9476-0FDEC0F6BB1D](https://user-images.githubusercontent.com/2647926/80892902-a69d6400-8cc5-11ea-944a-a418e696d2d7.png)

**Comment by upwindanderl** [comment]
**NO WAY !!!!! 
Sorry.... i read your advise first and searched for sth like this but didn't found any hint**

Now i see! So easy 
THANK YOU SO MUCH..
