### ISSUE TITLE
Add to HACS

### ISSUE THREAD

**Issue by vlumikero** [fwestenberg/reolink#42]
That would be a major convenience. Let me know if you need help with that, I just added my first HACS component :)

Thanks for the great work so far!

**Comment by gregoryduckworth** [comment]
https://github.com/fwestenberg/reolink/issues/39

**Comment by MattiasC** [comment]
The [PR](https://github.com/home-assistant/brands/pull/1727) to add the Reolink_dev to Home Assistant Brands have been accepted which was one of the prerequisites for HACS.

**Comment by fwestenberg** [comment]
@MattiasC I moved the repository because I'm working on a HA release version. Do you know how to change HACS?
