### ISSUE TITLE
Reolink RLN8-410-E NVR

### ISSUE THREAD

**Issue by KameDomotics** [fwestenberg/reolink#46]
Hi.
I have a Reolink RLN8-410-E NVR with v.2.0.0.249_20011608101 firmware (2020).

In configuration .yaml:
`camera:
- platform: reolink_dev
  host: 192.168.1.16  (my NVR IP)
  username: admin
  password: xxxxxxxxxxxxxxx
  name: CAM GIARDINO
  stream: main
  protocol: rtsp
  channel: 01
  scan_interval: '00:00:05'`

In lovelace:
`aspect_ratio: 0%
camera_image: camera.cam_giardino
entities:
  - camera.cam_giardino
    title: CAM GIARDINO
    type: picture-glance`

Now I can see entity “camera.cam_giardino”, but streaming don’t start.

**Comment by KameDomotics** [comment]
> Have you set `camera_view: live` in lovelace?

Yes, now it work fine thanks.

But with the wifi connection (same network) I can see the video well, outside my home with 4G connection it cannot show me the video (it only loads the static image very slowly). The cause may be the slowness of duckdns?

**Comment by Nowaker** [comment]
@KameDomotics Can you paste your final settings with proper formatting? I'd love to reuse yours. Thank you.

**Comment by KameDomotics** [comment]
> @KameDomotics Can you paste your final settings with proper formatting? I'd love to reuse yours. Thank you. 

`#REOLINK NVR
camera:
- platform: reolink_dev
  host: 192.168.1.16
  username: admin
  password: nvr password 
  name: cam giardino
  stream: sub
  protocol: rtsp
  channel: 00
  scan_interval: '00:00:05' 
  
- platform: reolink_dev
  host: 192.168.1.16
  username: admin
  password: nvr password 
  name: cam cortile
  stream: sub
  protocol: rtsp
  channel: 01
  scan_interval: '00:00:05' `

**Comment by Nowaker** [comment]
Sweet, thank you!
