### ISSUE TITLE
Installation via HACS fails

### ISSUE THREAD

**Issue by dhzl84** [fwestenberg/reolink#5]
Tested Versions 009, 008, 007 and MAIN
HACS Version: 1.6.2
HA Version: 0.117.6

Error message:
```
Logger: custom_components.hacs.repository.integration.fwestenberg.reolink
Source: custom_components/hacs/repositories/integration.py:88
Integration: HACS (documentation, issues)
First occurred: 4:20:12 PM (2 occurrences)
Last logged: 4:20:13 PM

No file found 'custom_components/None/manifest.json'
```
I was running version 007, upon update the integration was deleted and my configuration got invalid due to the absence of the _reolink_dev_ platform.

**Comment by gregoryduckworth** [comment]
I think this is due to https://github.com/home-assistant/core/pull/43195 where @fwestenberg is trying to get it as part of home-assistant (which is amazing BTW!) so it has bee completely rewritten.

**Comment by fwestenberg** [comment]
@gregoryduckworth You are right! The new Reolink integration supports config flow and a lot of new features, including real time push motion events! It also generates switches and a binary sensor, beside of PTZ services etc. Please be patient, for now you can use the library https://github.com/fwestenberg/reolink_dev (I had to move this one). The HACS integration should refer to this.

**Comment by dhzl84** [comment]
Really good to hear that, much appreciated!

Regarding the issue:

Installation worked with _reolink_dev_ repository but I there is a typo in the readme:

> 5. Paste the repository URL (https://github.com/fwestenberg/reolink) in the dialog box

Should be

> 5. Paste the repository URL (https://github.com/fwestenberg/reolink_dev) in the dialog box

IMHO

I submitted [PR 84](https://github.com/fwestenberg/reolink_dev/pull/84) for the fix.
