### ISSUE TITLE
[Feature Request] Spotlight support

### ISSUE THREAD

**Issue by ovid-io** [fwestenberg/reolink#58]
I'm wondering if anyone could implement spotlight support in this library? I have found this documentation here that might be of help https://home-cdn.reolink.us/wp-content/uploads/2021/05/070123211620350601.5874.docx

It references SetWhiteLed command, which is what my cameras web interface is sending when trying to configure the backlight. I have no experience with python but there is reolink_dev home assistant integration that I would like to attempt to integrate this feature in

**Comment by rchiileea** [comment]
is this going to happen?

**Comment by ptyers** [comment]
#68 

Work in progress - a pull request which I think handles spotlight has been submitted. Nothing re Siren yet

**Comment by rchiileea** [comment]
Cool I have this camera in back yard so it could be used as a light through this for me

**Comment by ptyers** [comment]
Ver 0.45 now includes WhiteLed (Spotlight) support

**Comment by cpainchaud** [comment]
implemented, thx @ptyers
