### ISSUE TITLE
Camera Picture Entity corrupt after camera reboot

### ISSUE THREAD

**Issue by d3wy** [fwestenberg/reolink#60]
I've identified this occurring as a result of a scheduled camera reboot on my camera. However I can reproduce it with a 'reboot' command on the camera web interface.

Camera's entity_picture (/api/camera_proxy/....) serves a corrupted image following connection loss. When clicking on the camera in home assistant it still loads the live stream and motion events seem to continue, however the only way to recover the entity_picture is a reboot of home assistant?

```
<img src="https://[redacted]/api/camera_proxy/camera.garage4?token=[redacted]" alt="The image “https://[redacted]/api/camera_proxy/camera.garage4?token=[redacted]” cannot be displayed because it contains errors." title="" width="inherit" height="inherit">
```

HA Version: Home Assistant 0.114.0 (this has occurred on earlier versions also)

**Comment by IvanPenyaHuguet** [comment]
I can confirm it, I don't know why it doesn't reconnect once the cam is up. As documentation, we can get if the autoreboot is enabled with the api: `cmd=GetAutoMaint`.
Getting this information:
`[ { "cmd" : "GetAutoMaint", "code" : 0, "value" : { "AutoMaint" : { "enable" : 0, "hour" : 2, "min" : 0, "sec" : 0, "weekDay" : "Sunday" } } } ]`

**Comment by IvanPenyaHuguet** [comment]
I have pulled a solution for this issue, it is now live in this release. If you can confirm that it works fine now this can be closed.

**Comment by rednus** [comment]
Hi Ivan, this now works after camera reboot. Thank you.

**Comment by d3wy** [comment]
Great work @IvanPenyaHuguet and thank you. Sorry I was a little slow to respond to this and the bug report was a little light on, it's my first bug report. But I can confirm with A/B testing (rebooted camera and no reconnect, I then installed v0.5 of the plugin and rebooted the camera and connection was restored) that this issue is closed.
