### ISSUE TITLE
No Video - Errors In log, IP address works fine

### ISSUE THREAD

**Issue by JohnGalt1717** [fwestenberg/reolink#7]
Hi there, I have everything setup and everything except for video displays (and the buttons just throw errors. I have a Reolink 420

Here's my config (binary_sensor and switch are both in my configuration.yaml file and appear to validate and work fine otherwise)

camera:
  - platform: reolink
    name: entry_way_camera
    host: 192.168.x.x
    username: <login>
    password: <password>

I have verified that going to the IP on port 80 with the login and password copied and pasted from the config file works fine. (although flash.. yuk)

Here's the errors

2019-10-27 16:39:58 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink/camera.py", line 251, in get_camera_settings
    if (self._ir_lights[0]["value"]["IrLights"]["state"] == "Auto"):
KeyError: 'value'
2019-10-27 16:39:58 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 273, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/reolink/camera.py", line 168, in state_attributes
    attrs["ir_lights_enabled"] = self._ir_lights_enabled
AttributeError: 'ReolinkCamera' object has no attribute '_ir_lights_enabled'

There's nothing in the logs about the camera itself, just the ir_lights_enabled.

**Comment by JohnGalt1717** [comment]
Also, here's my card:

aspect_ratio: 0%
camera_image: camera.entry_way_camera
entities:
  - switch.camera_frontdoor_ir_lights
  - switch.camera_frontdoor_email
  - switch.camera_frontdoor_ftp
  - binary_sensor.motion_entry_way_camera
title: Entryway Camera
type: picture-glance

**Comment by JohnGalt1717** [comment]
I changed lin 251 of camera.py to the following:

        if (self._ir_lights and 'value' in self._ir_lights[0] and self._ir_lights[0]["value"]["IrLights"]["state"] == "Auto"):

Once this was done, it works fine. I suspect that the 420 doesn't have ir light control or it's configured differently.  Mine apparently doesn't have a self._ir_lights[0]["value"] property.

**Comment by fwestenberg** [comment]
Hi @JohnGalt1717 
Thanks for your input! As soon as I have some time left, I will start fixing some bugs! This certainly helps! Also I found out the Reolink camera's do send notifications when using ONVIF, so this is also something I'm trying to figure out.

**Comment by JohnGalt1717** [comment]
Realtime notifications without email would be awesome!  I'm a hack at best at python but always willing to learn a new language if there is anything you need help with.

**Comment by fwestenberg** [comment]
Please take a look at the 3rd post here (from Marlon): https://community.athom.com/t/subscribing-to-onvif-motion-detection-events/6507

I installed this software and found out Reolink actually triggers those events. So now we should find a way to subscribe...

**Comment by JohnGalt1717** [comment]
Here's what home assistant says about it. Although it looks like it was never done: https://github.com/home-assistant/home-assistant/issues/23656

At that point would we even need a special version for reolink? Wouldn't it be better to just make sure that reolink works with the onvif stuff and update it as appropriate to work with notifications as well?

**Comment by fwestenberg** [comment]
Hello guys, I just updated the Reolink integration. Notifications without e-mail are working now. Please let me know of this issue can be closed.

**Comment by fwestenberg** [comment]
@JohnGalt1717  is this issue still present?
