### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by PortScanner** [fwestenberg/reolink#72]
How can i install the Api on a RaspberryPi? Please Show me the correct way.
Thank you

**Comment by cpainchaud** [comment]
pip install reolink

**Comment by PortScanner** [comment]
aiohttp requires Python '>=3.4.2' but the running Python is 2.7.16

**Comment by cpainchaud** [comment]
Install et use python3.4+ then

**Comment by PortScanner** [comment]
pip3 install reolink
My Code:
import reolink
from reolink.camera_api import Api
if __name__ == "__main__":
    api = reolink.camera_api.Api('192.168.178.xx', 80, 'admin', 'xxxxxx')

Result:
pi@raspberrypi:~ $ python3 reo.py
Traceback (most recent call last):
  File "reo.py", line 3, in <module>
    from reolink.camera_api import Api
  File "/home/pi/.local/lib/python3.7/site-packages/reolink/camera_api.py", line 8, in <module>
    from . import typings
  File "/home/pi/.local/lib/python3.7/site-packages/reolink/typings.py", line 3, in <module>
    from typing import TypedDict
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/lib/python3.7/typing.py)

**Comment by cpainchaud** [comment]
Hi,

Use python 3.8 or install typing_extensions. You might want to google a bit your errors before asking for help.

**Comment by PortScanner** [comment]
Ok, Thank You
