### ISSUE TITLE
"entity_id" is deprecated by Home Assistant 0.115

### ISSUE THREAD

**Issue by atijaja** [fwestenberg/reolink#72]
Logger: homeassistant.components.template.binary_sensor
Source: helpers/config_validation.py:752
Integration: template (documentation, issues)
First occurred: 26. September 2020, 21:38:46 (2 occurrences)
Last logged: 26. September 2020, 21:38:46
The 'entity_id' option is deprecated, please remove it from your configuration 

https://community.home-assistant.io/t/heads-up-upcoming-breaking-change-in-the-template-integration/223715

**Comment by fwestenberg** [comment]
I've planned to update the integration with integration flow and perhaps discovery. Adding the Reolink will probably result in:
- Binary sensors
- Switches
- Camera -> onvif

Also, hopefully the Onvif integration will be fixed so the motion event will can be used for motion detection.

**Comment by atijaja** [comment]
thanks 
for the moment i solved it like this
I removed the "entity_id: camera.frontdoor" from the config under "binary_sensor"

binary_sensor:
  platform: template
  sensors:
    motion_frontdoor:
      friendly_name: Camera frontdoor
      device_class: motion
      # entity_id: camera.frontdoor
      value_template: "{{ is_state('camera.frontdoor', 'motion') }}"
      delay_off: 
          seconds: 30


everything seems to work and the warning is gone
