### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by fabaff** [fwestenberg/reolink#78]
**Describe the bug**

The current version is [0.0.53](https://github.com/fwestenberg/reolink/blob/main/setup.py#L6). The GitHub release is [0053](https://github.com/fwestenberg/reolink/releases/tag/v0053) while named `v0.53`.

Please tag the releases on GitHub with the exact version number. Otherwise it causes trouble for the distributions which are shipping this module as package.

Thanks 

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version
 - Reolink camera model
 - Camera firmware number

**Additional context**
n/a

**Comment by cpainchaud** [comment]
interesting, I just kept numbering as it was initiated by the creator of this library. New release is now using 'v0.X' in release name and tag
