### ISSUE TITLE
Retrieve still image after motion is detected

### ISSUE THREAD

**Issue by rangulvers** [fwestenberg/reolink#80]
First I want to say : GREAT JOB!! the extension works great. 

After playing around with the motion detection I wanted to setup a notification to my phone and attaching a still image fromt he moment the motion was detected. 

How can I retrieve the still image? Do you have any guidance on this?

**Comment by fwestenberg** [comment]
You can just use the service camera.snapshot for this.

**Comment by rangulvers** [comment]
in case somebody else is looking for the same topic. 
After playing around with the camera.snapshot option for a while and not getting it to work as I would like. I have the following flow setup in node red

Listen to the state_changed event for the camera if motion is detected----get the current state of the camera---edit the message with a function node---send mobile notification

The "get current state" node is needed to retrieve the "msg.data.attributes.entity_picture" from the camera entity

Code for the function node
msg.payload = {
    "data":{
        "title":"BEWEGNUNG ERKANNT",
        "message":msg.data.attributes.friendly_name,
        "data":{
            "ttl":0,
            "priority": "high",
             "channel": "Motion",
             "importance": "high",
             "ledColor": "red",
            "image":"https://{your haas url}:8123"+msg.data.attributes.entity_picture 
        }
    }
}
return msg;
